### ISSUE TITLE
I'm fuddled

### ISSUE THREAD

**Issue by ohlawdie** [miyliyevr/youtubeChapterRewind#2]
I know this isn't helpful but your script doesn't seem to be working for some reason I've tried to troubleshoot as much as I could: as for all of my efforts I've tried with TamperMonkey in firefox, chrome, and vivaldi -- thank you

**Comment by miyliyevr** [comment]
> I know this isn't helpful but your script doesn't seem to be working for some reason I've tried to troubleshoot as much as I could: as for all of my efforts I've tried with TamperMonkey in firefox, chrome, and vivaldi -- thank you

May be TamperMonkey is conflicting with another extension. 
Let's see if there are problems of browser/TamperMonkey settings.
You said that you tried different browsers, but I would still recommend trying it in incognito mode and having only this script enabled in Tampermonkey. Also make sure Javascript is enabled for the browser.
Try it with the video in Youtube that is having chapters (this script is not going to play the next video upcoming in recommendations, nor the next video on your playlist).
You should see that TamperMonkey extension icon will have a '1' over it, showing that there is one script that is connected to this web page address.
After video starts playing, hover the mouse over it so you see the playback timeline and then try pressing 'n' on your keyboard.
Let me know if this works.

**Comment by Avivhdr** [comment]
They 👂  you 
😄
 

![image](https://user-images.githubusercontent.com/23265867/130325036-b0e76653-3132-44ee-9aea-ad1547ea160e.png)

**Comment by miyliyevr** [comment]
Wow, it's so great. Thank you for informing!
I can remove TamperMonkey now))
Previously when I started doing some stuff for the Chrome, some time later Google introduced it, so I stopped working on it.
Here it happens again, great job Google)))

**Comment by Avivhdr** [comment]
Big wheels turn slow...

Good for you for solving it yourself 👏
